// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsrC7iKgx6zkEsG8uby86iIU0cQ9qPmI',
    appId: '1:526977671424:web:0a0b0b77fba9aa2eb8d3e5',
    messagingSenderId: '526977671424',
    projectId: 'diary-me-490004',
    authDomain: 'diary-me-490004.firebaseapp.com',
    storageBucket: 'diary-me-490004.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KvZfDaKcEYqveHhaR_GyTyo6qMi-ASY',
    appId: '1:526977671424:android:721cbe07d78afb9fb8d3e5',
    messagingSenderId: '526977671424',
    projectId: 'diary-me-490004',
    storageBucket: 'diary-me-490004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_RCSRbayT8ce0UEyrDr0yieotYAOMfE',
    appId: '1:526977671424:ios:01cc62001139b9b9b8d3e5',
    messagingSenderId: '526977671424',
    projectId: 'diary-me-490004',
    storageBucket: 'diary-me-490004.firebasestorage.app',
    iosClientId: '526977671424-7rmc34tgi4r21bisg928ii8lbo8thre5.apps.googleusercontent.com',
    iosBundleId: 'com.yourname.noYouAreNot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP_RCSRbayT8ce0UEyrDr0yieotYAOMfE',
    appId: '1:526977671424:ios:1869a3077b1b6e39b8d3e5',
    messagingSenderId: '526977671424',
    projectId: 'diary-me-490004',
    storageBucket: 'diary-me-490004.firebasestorage.app',
    iosClientId: '526977671424-cf12ma97csh6cup8fthde9inmtl03mc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIsrC7iKgx6zkEsG8uby86iIU0cQ9qPmI',
    appId: '1:526977671424:web:87502b414ff4845db8d3e5',
    messagingSenderId: '526977671424',
    projectId: 'diary-me-490004',
    authDomain: 'diary-me-490004.firebaseapp.com',
    storageBucket: 'diary-me-490004.firebasestorage.app',
  );
}
